### ISSUE TITLE
argument 'index' is out of range

### ISSUE THREAD

**Issue by aujiz11** [IS4Code/PawnPlus#57]
I use the dynamic container `list` to store the list of vehicles, however when using `list_get_arr_safe` to check and get data from `index` an error occurs.

```
[Info] [PawnPlus] Warning: amx_FindPublic returned negative index -10063 for function 'pp_on_error'. Possible collision with SAMPGDK detected. Use pp_public_min_index or pp_use_funcidx to remove this warning.
[PawnPlus] list_get_arr_safe: argument 'index' is out of range
[Info] [debug] Run time error 10: "Native function failed"
```

Below is my code:
```
new resultData[E_PLAYER_VEHICLES];

for(new i; i < MAX_PLAYERVEHICLE_SLOT; i++)
{
    if (list_get_arr_safe(vehicles_list, i, resultData))
    {
        format(dialog_info, _, "%s\n", Model_Name(resultData[vehicle_Model]));
        continue;   
    }

    strcat(dialog_info, "Empty\n");
}
```

`MAX_PLAYERVEHICLE_SLOT` is the number of player vehicle storage slots (default: 10)

**Comment by IS4Code** [comment]
Hello, how do you construct the list? Is `index` within the bounds of the list, i.e. `0 <= index < list_size(vehicles_list)`?

**Comment by aujiz11** [comment]
> Xin chào, bạn xây dựng danh sách như thế nào? Có nằm `index`trong giới hạn của danh sách không `0 <= index < list_size(vehicles_list)`?

Index may not be in the `list`, because I want it to create a dialog box containing 10 vehicle storage lines, so I use a loop from 0 -> 9 and check if the index exists or not. But maybe `list_get_arr_safe` doesn't do the checking, so how can I check the index?
