### ISSUE TITLE
[Request]: New natives

### ISSUE THREAD

**Issue by Tiaansu** [IS4Code/PawnPlus#60]
Hi, I think it will be better if PP's containers has `*_has` native to check if the index is existing or not.

List of natives:
```pawn
// List
native bool:list_has(List:list, index);

// Linked List
native bool:linked_list_has(List:list, index);
```

**Comment by IS4Code** [comment]
Hello, is there a particular need for the natives here? You could do the same easily with a macro:
```pawn
#define list_has(%0, %1) (0 <= (%1) < list_size(%0))
```
Native `list_has` could probably be added if needed, but I am interested in its use-cases. How often is it needed in practice? Do you use variable-sized lists in situations where optional indices may be useful and so you need to branch depending on the presence of elements? Could pools be used in the same situations?

As for `linked_list_has`, I am slightly more against it, as you should not use indices at all when working with linked lists. I would rather make such functions opt-in. Do you have an example of code where you would use this function?

**Comment by Tiaansu** [comment]
1. Well, it is not needed but I thought it would be best if I suggest it. The use-cases of it can also be done using pools so, I think it's not needed anymore.

2. In the `linked_list_has` one, I also just thought I can include it here because I suggested for the `list_has`. And no, I don't have an example code as I don't use it often.

thanks for the macro btw.
